#Aqui irei definir o nome do pipeline
name: Meu primeiro workflow
#Quais eventos (gatilhos disparam o fluxo?
# temos eventos do tipo push, pull request, merge, rebase...
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches:
      - main
      - master
      - develop
# Quais são as tarefas a serem executadas pelo workflow?
jobs:
  tarefa1:
    name: Primeira tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 2
        run: echo "Executando o passo1"
      - name: Passo 2
        run: echo "Executando o passo2"
      - name: Passo 3
        run: echo "Executando o passo3"
  tarefa2:
    name: Segunda tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 4
        run: echo "Executando o passo4"
      - name: Passo 5
        run: echo "Executando o passo5"
      - name: Passo 6
        run: echo "Executando o passo6"
  tarefa3:
    name: Terceira tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 7
        run: echo "Executando o passo7"
      - name: Passo 8
        run: echo "Executando o passo8"
      - name: Passo 9
        run: echo "Executando o passo9"
